### PR TITLE
Fix: Add defensive null checks for queue variables (Issue #299)

### LINKED ISSUE #299: Errors caused by _suspensionQueue being undefined
If I attempt using the extension after a period of inactivity, the service worker would sometimes get stuck in the Inactive state (ignoring user actions and displaying a suspended pages as blank). Checking it in Extensions view shows two `TypeError`s within `js/gsTabSuspendManager.js` (lines 60/`unqueueTabForSuspension()` & 204/`getQueuedTabDetails()`): "_Cannot read properties of undefined_" (both pointing at methods of `_suspensionQueue`).

It appears that `_suspensionQueue` might not be re-initialized correctly when restoring service worker that was [unloaded from memory](https://developer.chrome.com/docs/extensions/develop/concepts/service-workers/lifecycle#idle-shutdown) 🤔

### PR DESCRIPTION
**Pull request by bbleak-repo**
## Summary

Adds defensive null checks to prevent TypeErrors when Chrome's service worker lifecycle unloads and restarts the extension during idle periods.

## Problem

When the service worker is unloaded by Chrome (Memory Saver, idle timeout, etc.), the queue variables (`_suspensionQueue`, `_tabCheckQueue`, `_discardQueue`) become undefined. If any queue method is called before `initAsPromised()` completes on restart, a TypeError occurs:

```
TypeError: Cannot read properties of undefined (reading 'unqueueTab')
    at unqueueTabForSuspension (gsTabSuspendManager.js:60)
```

## Solution

Added null checks at the entry point of all public functions that access the queue variables. Functions now gracefully return early (with appropriate logging) if the queue hasn't been initialized yet.

## Files Changed

- `src/js/gsTabSuspendManager.js` - 4 functions protected
- `src/js/gsTabCheckManager.js` - 4 functions protected  
- `src/js/gsTabDiscardManager.js` - 2 functions protected

## Testing

- [ ] Tested with Chrome's Memory Saver enabled
- [ ] Verified no TypeErrors after idle periods
- [ ] Extension recovers gracefully when service worker restarts

> **Note:** Currently testing this fix - will update with results. Opening PR now to track the fix and get feedback on the approach.

Fixes #299

### CODE REVIEW

**Comment by ossilator** [comment]
you should also document what happens next, i.e., whether/how the extension recovers gracefully from that state.

**Comment by rkodey** [comment]
Hello @bbleak-repo !
Thanks for the defense checks!

I'm curious if you encountered a situation where any of the 3 tab "Managers" caused an error without these checks?

I thought a lot about the 3 tab Managers during the conversion to Manifest V3, knowing that the service worker can suspend and restart.  According to this page, the worker won't suspend if there's certain activity:
https://developer.chrome.com/docs/extensions/develop/migrate/to-service-workers?hl=en#keep_a_service_worker_alive_until_a_long-running_operation_is_finished

...and since the Managers generally use a short timeout/pause, any 1 of the 3 Managers _should_ keep the service worker alive as long as tabs are waiting to be processed.

BUT...  what about if the queues are all empty?  For sure the service worker WILL suspend.  In these cases, in all my tests the 3 Manager queues all re-initialized themselves as the service worker began its processing again.  So far I haven't seen the new null checks catch any cases.  ( I will still merge them in anyway. )


NOTE:  The reason I'm asking is there are a couple of open Favicon related issues, and I'm trying to see if these null checks might solve one or more of them.

**Review by rkodey — APPROVED** [review]

**Comment by rkodey** [comment]
All 3 queues are always reinitialized when the service worker is re-activated.
I haven't been able to provoke the error in #299 yet -- perhaps it's a race condition.

I'm thinking that instead of having the null checks simply return, maybe have them re-initialize.  Testing...

File: src/js/gsTabCheckManager.js [hunk 1]
```diff
@@ -259,7 +273,7 @@ export const gsTabCheckManager = (function() {
 
     let reinitialised = false;
     if (!tabChecksOk) {
-      const tabQueueDetails = _tabCheckQueue.getQueuedTabDetails(tab);
+      const tabQueueDetails = getQueuedTabCheckDetails(tab);
```
Comment (rkodey) [inline src/js/gsTabCheckManager.js:276]: 👍

File: src/js/gsTabCheckManager.js [hunk 2]
```diff
@@ -373,7 +387,7 @@ export const gsTabCheckManager = (function() {
       return;
     }
 
-    const queuedTabDetails = _tabCheckQueue.getQueuedTabDetails(tab);
+    const queuedTabDetails = getQueuedTabCheckDetails(tab);
```
Comment (rkodey) [inline src/js/gsTabCheckManager.js:390]: 👍
